# Generated by Django 5.2.10 on 2026-02-01 11:58

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Page content')),
            ],
            options={
                'verbose_name': 'Policy Page',
                'verbose_name_plural': 'Policy Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Column title/heading', max_length=255)),
                ('column_type', models.CharField(choices=[('menu', 'Menu Links'), ('text', 'Text Content'), ('custom', 'Custom HTML')], default='menu', help_text='Type of content for this column', max_length=50)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Rich text content (for Text Content type)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in footer')),
                ('menu', models.ForeignKey(blank=True, help_text='Select a menu (for Menu Links type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.navigationmenu')),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('link_url', models.CharField(blank=True, help_text='Custom URL (used if no page is selected)', max_length=255)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.navigationmenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color code for primary theme', max_length=20)),
                ('secondary_color', models.CharField(default='#ffffff', help_text='Hex color code for secondary theme', max_length=20)),
                ('font_family', models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('mono', 'Monospace')], default='sans-serif', max_length=100)),
                ('contact_address', models.CharField(default='925 Filbert Street Pennsylvania 18072', help_text='Physical address', max_length=255)),
                ('contact_phone', models.CharField(default='+ 45 34 11 44 11', help_text='Phone number', max_length=50)),
                ('contact_email', models.EmailField(default='info@gmail.com', help_text='Contact email address', max_length=254)),
                ('social_facebook', models.URLField(blank=True, help_text='Facebook URL')),
                ('social_twitter', models.URLField(blank=True, help_text='Twitter URL')),
                ('social_instagram', models.URLField(blank=True, help_text='Instagram URL')),
                ('footer_description', models.TextField(blank=True, help_text='Description text for the footer logo section')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('footer_logo', models.ForeignKey(blank=True, help_text='Logo to display in the footer (usually white/light version)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('privacy_policy_page', models.ForeignKey(blank=True, help_text='Link to Privacy Policy page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('terms_conditions_page', models.ForeignKey(blank=True, help_text='Link to Terms & Conditions page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
