# Generated by Django 5.2.11 on 2026-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebrandingsettings',
            name='contact_phone',
            field=models.CharField(help_text='Phone number', max_length=50),
        ),
    ]
