# Generated by Django 5.2.11 on 2026-02-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitebrandingsettings_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebrandingsettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50, null=True),
        ),
    ]
