# Generated by Django 5.2.11 on 2026-03-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitebrandingsettings_contact_phone'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebrandingsettings',
            name='cookie_policy_page',
            field=models.ForeignKey(blank=True, help_text='Link to Cookie Policy page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
