# Generated by Django 5.2.10 on 2026-02-01 11:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Brief introduction text for the homepage')),
                ('body', wagtail.fields.StreamField([('hero', 9), ('logo_cloud', 13), ('stats', 15), ('services', 21), ('whitepapers', 24), ('testimonials', 26), ('networks', 28), ('newsletter', 34)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hero section title', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hero section subtitle', 'max_length': 500, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for hero section'}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 40, 'help_text': 'Opacity of dark overlay (0-100)', 'max_value': 100, 'min_value': 0}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('outline', 'Outline'), ('white', 'White')]}), 7: ('wagtail.blocks.StructBlock', [[('text', 4), ('link', 5), ('button_style', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('overlay_opacity', 3), ('cta_buttons', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title', 'max_length': 255}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Our Clients', 'help_text': 'Display label for clients', 'max_length': 100}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 11), ('section_title', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': '#E7ECEF', 'help_text': 'Hex color code', 'max_length': 7}), 15: ('wagtail.blocks.StructBlock', [[('background_color', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "Main heading (e.g., 'We provide that service.')", 'max_length': 255}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Description text for the left column', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'help_text': 'Call-to-action button text', 'max_length': 100, 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL for the CTA button', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': '#F5F7FA', 'help_text': 'Background color for service cards section (hex code)', 'max_length': 7}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('description', 17), ('cta_text', 18), ('cta_url', 19), ('background_color', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Latest Whitepapers', 'max_length': 255}), 23: ('wagtail.blocks.IntegerBlock', (), {'default': 6, 'help_text': 'Number of whitepapers to display'}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('subtitle', 11), ('limit', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'max_length': 255}), 26: ('wagtail.blocks.StructBlock', [[('title', 25), ('subtitle', 11)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Connect With Us', 'max_length': 255}), 28: ('wagtail.blocks.StructBlock', [[('title', 27), ('subtitle', 11)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to Our Newsletter', 'max_length': 255}), 30: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'default': 'Enter your email address', 'max_length': 100}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'max_length': 50}), 33: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 29), ('subtitle', 11), ('description', 30), ('placeholder', 31), ('button_text', 32), ('background_image', 33)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='fab fa-linkedin', help_text='Bootstrap icon class (e.g., fab fa-linkedin, fab fa-twitter)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.ForeignKey(blank=True, help_text='Icon for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, choices=[('%', '%'), ('k', 'k'), ('+', '+'), ('x', 'x'), ('M+', 'M+'), ('', 'None')], default='', help_text='Symbol to display after the value (e.g., %, k, +)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description text for the statistic (e.g., "Follow a hashtag growth total posts, videos and images.")')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.ForeignKey(blank=True, help_text='Icon for this statistic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'Stats Counters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.fields.RichTextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(blank=True, max_length=255)),
                ('author_company', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('author_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
