# Generated by Django 5.2.10 on 2026-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statscounter',
            name='symbol',
            field=models.CharField(blank=True, choices=[('%', '%'), ('k', 'k'), ('k+', 'k+'), ('+', '+'), ('x', 'x'), ('M+', 'M+'), ('', 'None')], default='', help_text='Symbol to display after the value (e.g., %, k, +)', max_length=10),
        ),
    ]
