# Generated by Django 5.2.10 on 2026-02-03 05:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('two_column', 3), ('process_section', 8), ('rich_text', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 0), ('icon', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 4), ('features', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Us Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
