# Generated by Django 5.2.10 on 2026-02-04 21:03

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitepaperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'whitepaper categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhitepaperClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('website', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'whitepaper clients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhitepaperIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('hero_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WhitepaperPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Publish date')),
                ('template_content', wagtail.fields.StreamField([('default', 15), ('aws', 21), ('lenovo', 25)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Download Now'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Used as the field name in the database (e.g. 'first_name')", 'required': True}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')]}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('label', 8), ('value', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Only used for Select and Radio fields', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 0), ('name', 4), ('field_type', 5), ('required', 6), ('placeholder', 7), ('choices', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'required': False}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Thank You!'}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('background_image', 2), ('form_title', 3), ('form_fields', 12), ('pdf_file', 13), ('thank_you_title', 14), ('thank_you_text', 1), ('cta_text', 3)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Appears in the blue bar', 'required': True}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Download the eBook'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'I am completing this form in connection with my:'", 'required': False}), 20: ('wagtail.blocks.ListBlock', (9,), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('logo', 2), ('hero_title', 16), ('intro_text', 1), ('cover_image', 17), ('landing_description', 1), ('form_title', 18), ('form_fields', 12), ('interest_question', 19), ('interest_options', 20), ('consent_text', 1), ('privacy_notice', 1), ('pdf_file', 13), ('thank_you_title', 14), ('thank_you_text', 1), ('cta_text', 18)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 23: ('wagtail.blocks.RichTextBlock', (), {}), 24: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('heading', 8), ('subheading', 7), ('background_image', 22), ('intro_text', 23), ('highlights', 24), ('form_title', 3), ('form_fields', 12), ('pdf_file', 13), ('thank_you_title', 14), ('thank_you_text', 1), ('cta_text', 3)]], {})}, help_text='Select a theme and fill in its content.')),
                ('is_featured', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='whitepapers.whitepapercategory')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whitepapers.whitepaperclient')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
