# Generated by Django 5.2.10 on 2026-02-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.downloadtoken')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField()),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('referer', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('exported', 'Exported'), ('contacted', 'Contacted'), ('qualified', 'Qualified')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whitepaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='whitepapers.whitepaperpage')),
            ],
            options={
                'unique_together': {('whitepaper', 'email')},
            },
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.lead'),
        ),
        migrations.CreateModel(
            name='LeadFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, help_text='Slug of the field from the template block', max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='whitepapers.lead')),
            ],
        ),
        migrations.CreateModel(
            name='WhitepaperView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('whitepaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitepapers.whitepaperpage')),
            ],
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token'], name='whitepapers_token_3077c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadfieldvalue',
            unique_together={('lead', 'field_name')},
        ),
    ]
