# Generated by Django 5.2.11 on 2026-02-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0003_alter_whitepaperpage_template_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaperview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
