# Generated by Django 5.2.11 on 2026-02-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0004_alter_whitepaperview_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
