# Generated by Django 5.2.11 on 2026-02-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0006_alter_whitepaperpage_template_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['whitepaper', 'email'], name='whitepapers_whitepa_f1dc50_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['submitted_at'], name='whitepapers_submitt_6a379d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='whitepapers_status_82e2f7_idx'),
        ),
    ]
