# Generated by Django 5.2.11 on 2026-02-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers', '0007_alter_lead_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaperview',
            name='whitepaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='whitepapers.whitepaperpage'),
        ),
    ]
